ScripLang/zad4/polls/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('news/<int:id>/', views.news, name='news'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ScripLang/zad4/zad4/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from users import views as user_views

urlpatterns = [
    path('', include('polls.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/login.html'), name='logout'),
    path('admin/', admin.site.urls),
]

ScripLang/zad4/polls/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
import os


def get_image_path(instance, filename):
    return os.path.join(str(instance.id), filename)

# Create your models here.


class News(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.TimeField(default=timezone.now)
    photo = models.ImageField(upload_to=get_image_path, blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    news = models.ForeignKey(News, on_delete=models.CASCADE)
    date_posted = models.TimeField(default=timezone.now)
    content = models.TextField()

ScripLang/zad4/users/models.py
from django.db import models

# Create your models here.

ScripLang/zad4/polls/forms.py
from django.forms import ModelForm
from .models import Comment


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['author', 'news', 'content']

ScripLang/zad4/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

ScripLang/zad4/polls/views.py
from django.shortcuts import render, redirect
from .models import News, Comment
from .forms import CommentForm
from django.contrib import messages

from django.http import HttpResponse


# Create your views here.
def index(request):
    context = {
        'news': News.objects.all()
    }
    return render(request, 'polls/index.html', context=context)


def about(request):
    return render(request, 'polls/about.html')


def news(request, id):
    if request.method == 'GET':
            context = {
                'news': News.objects.filter(id=id)[0],
                'comments': Comment.objects.filter(news=id),
                'form': CommentForm()
            }
            return render(request, 'polls/news.html', context)
    elif request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Skomentowałeś artykuł.")
            return redirect(request.path)

    return redirect('index')

ScripLang/zad4/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserRegisterForm


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, 'Utworzono konto dla {}! Teraz możesz się zalogować!'.format(username))
            return redirect('login')

    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})

ScripLang/zad4/templates/polls/about.html
{% extends "polls/base.html" %}
{% block content %}
    Strona powstała na potrzeby przedmiotu 'Języki Skryptowe I Ich Zastosowania'
{%  endblock content %}

ScripLang/zad4/templates/polls/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'polls/main.css' %}">
    <title>WWZP</title>
</head>
<body>
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top align-right">
        <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'index' %}">Wiadomości Wyssane Z Palca</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{% url 'index' %}">Strona Główna</a>
                    <a class="nav-item nav-link" href="{% url 'about' %}">O Stronie</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                        <a class="nav-item nav-link">Zalogowany jako {{ user.username }}</a>
                        <a class="nav-item nav-link" href="{% url 'logout' %}">Wyloguj</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{% url 'login' %}">Zaloguj</a>
                        <a class="nav-item nav-link" href="{% url 'register' %}">Rejestruj</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>
<main role="main" class="container">
    <div class="row">
        <div class="col-md-20">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
        </div>
    </div>
</main>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</body>
</html>

ScripLang/zad4/templates/polls/index.html
{% extends "polls/base.html" %}
{% block content %}
    {% for ne in news %}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2 ">{{ ne.author }}</a>
                    <small class="text-muted">{{ ne.date_posted|date:"F d, Y" }}</small>
                </div>
                <h2><a class="article-img"><img src="{{ ne.photo.url }}"/> </a></h2>
                   <h2> <a class="article-title" href="/news/{{ ne.id }}">{{ ne.title }}</a></h2>
                <p class="article-content">{{ ne.content }}</p>
            </div>
        </article>
    {% endfor %}
{% endblock content %}

ScripLang/zad4/templates/polls/news.html
{% extends "polls/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2 ">{{ news.author }}</a>
                <small class="text-muted">{{ news.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-img"><img src="{{ news.photo.url }}"/> </a></h2>
            <h2><a class="article-title" href="#">{{ news.title }}</a></h2>
            <p class="article-content">{{ news.content }}</p>
        </div>
    </article>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h3>Komentarze:</h3>
            </div><!-- /col-sm-12 -->
        </div><!-- /row -->
        {% for comment in comments %}
            <div class="row">
                <div class="col-sm-1">
                    <div class="thumbnail">
                        <img class="img-responsive user-photo" src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png">
                    </div><!-- /thumbnail -->
                </div><!-- /col-sm-1 -->

                <div class="col-sm-5">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <strong>{{ comment.author }}</strong>
                            <span class="text-muted">{{ comment.date_posted }}</span>
                        </div>
                        <div class="panel-body">
                            {{ comment.content }}
                        </div><!-- /panel-body -->
                    </div><!-- /panel panel-default -->
                </div><!-- /col-sm-5 -->
            </div><!-- /row -->
        {% endfor %}
        <div class="row">
            <form method="POST">
                {% csrf_token %}
                <div class="col-sm-20">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <fieldset class="form-group">
                                <legend class="border-bottom mb-4">Dodaj komentarz:</legend>
                                <div id="div_id_content" class="form-group">
                                    <input type="hidden" name="author" value="{{ user.id }}">
                                    <input type="hidden" name="news" value="{{ news.id }}">
                                    <label for="id_content" class="col-form-label  requiredField">
                                        Treść
                                    </label>
                                    <div class="">
                                        <textarea name="content" cols="40" rows="10" class="textarea form-control"
                                                  required="" id="id_content"></textarea>
                                    </div>
                                </div>
                                {#                                {{ form|crispy }}#}
                            </fieldset>
                            <div class="form-group">
                                <button class="btn btn-outline-secondary" type="submit">Skomentuj</button>
                            </div>
                        </div>
                    </div><!-- /panel panel-default -->
                </div><!-- /col-sm-5 -->
            </form>
        </div><!-- /row -->
    </div><!-- /container -->
{% endblock content %}

ScripLang/zad4/templates/users/login.html
{% extends "polls/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Logowanie</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Zaloguj się</button>
            </div>
        </form>
    </div>
{% endblock content %}

ScripLang/zad4/templates/users/logout.html
{% extends "polls/base.html" %}
{% block content %}
    <div class="content-section">
        <h2>Wylogowano pomyślnie!</h2>
    </div>
{% endblock content %}

ScripLang/zad4/templates/users/register.html
{% extends "polls/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Dołącz do najlepszej społeczności!</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Zarejestruj się</button>
            </div>
        </form>
    </div>
{% endblock content %}